import { regular } from '@/utils/fonts'
import { Metadata } from 'next'
import React from 'react'
export const metadata: Metadata = {
  title: 'hosenur • stack',
  description: 'Generated by create next app',
}
export default function Stack() {
  return (
    <div className={regular.className}>
      <p>MSI Modern A15M 2 TB SSD + 32 GB DDR4</p>
      <p>Apple iPhone 15 Plus 256 GB</p>
      <p>Samsung Galsxy A22 4G 128 GB</p>


      {/* <div className='flex flex-wrap gap-5'>
        <img src="/assets/obsidian.svg" className='w-10' alt="" />
        <img src="/assets/brave.svg" className='w-10' alt="" />
        <img src="/assets/wez.svg" className='w-10' alt="" />
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vim/vim-original.svg" className='w-10' alt="" />
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/fedora/fedora-original.svg" className='w-10' alt="" />
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg" className='w-10' alt="" />
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/chrome/chrome-original.svg" className='w-10' alt="" />
        <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/androidstudio/androidstudio-original.svg" className='w-10' alt="" />
        <img src="/assets/insomnia.svg" className='w-10' alt="" />

      </div> */}
    </div>
  )
}
