import React from 'react'

export default function About() {
  return (
    <div>
         Lorem, ipsum dolor sit amet consectetur adipisicing elit. Aliquam repellendus esse impedit, minus expedita, nulla maxime inventore perferendis numquam eos tenetur quia culpa harum adipisci laudantium et praesentium sint itaque quisquam vitae dolorem rem! Quidem alias est provident enim dolore exercitationem ex, fugit voluptate quaerat possimus, pariatur quasi error. Voluptates dolore mollitia rerum asperiores et. Blanditiis, necessitatibus consequuntur tempora, aspernatur atque quisquam mollitia odit magni omnis nobis eaque impedit perferendis iure vitae fugit maiores in harum perspiciatis quaerat fugiat aliquid eius tempore. Voluptas doloribus optio voluptatum ullam tempore nesciunt modi, dolorum esse, debitis neque explicabo quasi eum, vitae quam autem minus nihil aspernatur ratione natus tempora. Sed aperiam sunt ipsa laboriosam quis. Adipisci, voluptates non. Blanditiis aperiam sequi fugiat eum accusantium neque rerum quibusdam, corporis necessitatibus animi cupiditate ea, reiciendis qui distinctio fugit dolore! Consequuntur, a quod. Officia porro quaerat distinctio dolore corrupti? Incidunt, explicabo magnam, eligendi temporibus quia cum earum porro rem mollitia sapiente quaerat quam aperiam itaque eaque, animi commodi ipsam. Quidem iure possimus voluptas dolor quia aliquid maxime aspernatur officiis molestiae accusamus eveniet laborum ipsa nisi repellat ea, deserunt aperiam iste quis voluptate sequi vitae eius! Itaque corrupti nam obcaecati eligendi ipsam ea praesentium distinctio, optio fugiat at incidunt pariatur in officia minus accusamus, consequatur sint voluptatibus amet, accusantium natus nihil quis eveniet impedit possimus? Praesentium quasi, architecto, quo assumenda numquam minus dolore recusandae voluptatibus, similique dolorum debitis autem sint corrupti ab ad enim fugiat? Error laudantium quaerat mollitia repudiandae exercitationem nemo pariatur quas ea eveniet maiores, magni repellat facilis blanditiis eaque, aliquid consectetur odit obcaecati, aperiam ut animi dolor. Consectetur non dolorem debitis ab sunt expedita amet perspiciatis. Dolores adipisci illum, maxime repellendus iste quidem ipsam minima ut eos sequi, ad nam culpa explicabo cum eveniet facere deserunt fugiat doloremque rerum? Architecto et veritatis repellat harum!
    </div>
  )
}
