import { allProjects } from "@/.contentlayer/generated";
import Project from "@/components/Project";
import { regular, black } from "@/utils/fonts";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import React from 'react'
export const metadata: Metadata = {
  title: 'hosenur • projects',
  description: 'Generated by create next app',
}
export default function Projects() {
  return (
    <div className={"flex flex-col gap-10 " + regular.className}>
      <h1 className={black.className + " text-4xl md:text-5xl"}>Stuffs I Have Built</h1>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 group z-0">
        {allProjects.filter((project) => !project.draft).map((project) => (
          <Project key={project._id} project={project} />
        ))}
      </div>
    </div>
  )
}
