import { allProjects } from "@/.contentlayer/generated";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import React from 'react'
export const metadata: Metadata = {
  title: 'hosenur • projects',
  description: 'Generated by create next app',
}
export default function Projects() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-4 group z-0">
      {allProjects.filter((project) => !project.draft).map((project) => (
        <Link
          href={project.slug}
          className="flex flex-col gap-2"
          key={project._id}
        >
          <Image
            src={project.banner}
            alt="banner"
            width={1920}
            height={1440}
            className="group-hover:opacity-40 transition-opacity duration-300 hover:!opacity-100 rounded"
          />
          <h1>{project.title}</h1>
          <p>{project.description}</p>
        </Link>
      ))}
    </div>
  )
}
