import Header from '@/components/Header';
import './globals.css'
import { Analytics } from '@vercel/analytics/react';
import type { Metadata } from 'next'
import { ServerThemeProvider } from '@wits/next-themes'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes';


export const metadata: Metadata = {
  title: 'hosenur • home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider appearance={{
      baseTheme: dark
    }}>

      <ServerThemeProvider attribute='class' defaultTheme='dark'>


        <html lang="en">
          <body className={"max-w-6xl mx-auto p-5 lg:p-10 bg-zinc-900 text-zinc-100"}>
            <Header />
            {children}
            <Analytics />
          </body>
        </html>
      </ServerThemeProvider>
    </ClerkProvider>
  )
}
