import { db } from '@/utils/firebase';
import { collection, getDocs, orderBy, query } from 'firebase/firestore';
import { Metadata } from 'next';
import React from 'react'
async function getImages() {
    const images:any = [];
    const collectionRef = collection(db, "images");
    const q = query(collectionRef, orderBy("timestamp", "desc"));
    await getDocs(q).then((querySnapshot) => {
        querySnapshot.forEach((doc) => {
            images.push({
                id: doc.id,
                ...doc.data()
            });
        });
    }
    );
    return images;
}
export const metadata: Metadata = {
    title: 'hosenur • gallery',
    description: 'Generated by create next app',
  }
export default async function Gallery() {
    const images = await getImages();
    console.log(images);
    return (
        <div className='grid'>
            {
                images.map((image: any) => {
                    return (
                        <div key={image.id}>
                            hi
                        </div>
                    )
                })
            }
        </div>
    )
}
