import { Metadata } from 'next'
import React from 'react'
export const metadata: Metadata = {
  title: 'hosenur • blogs',
  description: 'Generated by create next app',
}
export default function Blogs() {
  return (
    <div>Blogs</div>
  )
}
