import { allBlogs } from '@/.contentlayer/generated'
import Blog from '@/components/Blog'
import { Metadata } from 'next'
import React from 'react'
export const metadata: Metadata = {
  title: 'hosenur • blogs',
  description: 'Generated by create next app',
}
export default function Blogs() {
  return (
    <div className='flex flex-col gap-2.5'>
      {allBlogs.filter((blog) => !blog.draft).map((blog) => {
        return (
          <Blog key={blog._id} blog={blog} />
        )
      }
      )}
    </div>)
}
