import Footer from "@/components/Footer";
import Header from "@/components/Header";
import Projects from "@/components/Projects";
import Stats from "@/components/Stats";
import { sanityClient } from "@/utils/sanity.client";
import Head from "next/head";
import Image from "next/image";
export default function Home({ data}: {data: any}) {
  console.log(data)
  return (
    <>
      <Header />
      <Head>
        <title>hosenur.io</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-5xl p-5 mx-auto font-bold space-y-10">
        <span>
          Hosenur - Full Stack Web Dev / Full Stack App Dev / Linux Enthusiast
        </span>
        <p className="text-4xl  md:text-6xl">
          I build <span className="gradient">super cool stuff</span> with the best and latest technologies
        </p>
        <Stats/>
        <Projects/>


      </main>
      <Footer />
    </>
  );
}

export const getStaticProps = async () => {
  const data = await sanityClient.fetch(`*[_type == "product"]`);
  return {
    props: {
      data,
    },
    revalidate: 10*60*60,
  };
};
