import { satoshi } from '@/utils/fonts'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={satoshi.className+" bg-zinc-900 text-zinc-200 p-10"}>
        <Header/>
        <main>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
